# Generated by Django 6.0.2 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gemini_api_key',
            new_name='llm_api_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_provider',
            field=models.CharField(
                choices=[
                    ('google-gemini', 'Google Gemini'),
                    ('openai', 'OpenAI'),
                    ('anthropic', 'Anthropic'),
                    ('mistral', 'Mistral'),
                    ('xai', 'xAI'),
                    ('qwen', 'Qwen'),
                    ('minimax', 'MiniMax'),
                    ('meta-llama', 'Meta Llama'),
                    ('other', 'Other'),
                ],
                default='google-gemini',
                max_length=32,
            ),
        ),
    ]
