# Generated by Django 6.0.2 on 2026-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chatfeedback_failure_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
