# Generated by Django 6.0.2 on 2026-10-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_conversation_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(default='gemini-3.8-flash', max_length=128),
        ),
    ]
