"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import dj_database_url
from cryptography.fernet import Fernet
from django.core.exceptions import ImproperlyConfigured
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


DEV_SECRET_KEY = "dev-only-change-me-secret-key"


def _csv_env(name, default=""):
    return [
        value.strip()
        for value in os.getenv(name, default).split(",")
        if value.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Keep JWT signing stable across local restarts when DJANGO_SECRET_KEY isn't set.
# Override with DJANGO_SECRET_KEY in production.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

render_external_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
default_hosts = "localhost,127.0.0.1" if DEBUG else render_external_hostname
ALLOWED_HOSTS = _csv_env("DJANGO_ALLOWED_HOSTS", default_hosts)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.UsageTrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

render_external_url = os.getenv("RENDER_EXTERNAL_URL", "").strip()
default_cors_origins = "http://localhost:3000" if DEBUG else render_external_url
CORS_ALLOWED_ORIGINS = _csv_env("DJANGO_CORS_ALLOWED_ORIGINS", default_cors_origins)
CORS_ALLOW_CREDENTIALS = True

FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "").strip()


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL:
    db_ssl_require_env = os.getenv("DJANGO_DB_SSL_REQUIRE", "").strip().lower()
    if db_ssl_require_env:
        db_ssl_require = db_ssl_require_env in ("1", "true", "yes")
    else:
        db_ssl_require = not DEBUG

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=db_ssl_require,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Proxy / HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    # HSTS — tell browsers to always use HTTPS for this domain.
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',
        'user': '30/minute',
        'chat': '10/minute',
    },
    'EXCEPTION_HANDLER': 'api.exception_handler.custom_exception_handler',
}

from datetime import timedelta

JWT_SIGNING_KEY_ENV = os.getenv("JWT_SECRET_KEY", "").strip()
JWT_SIGNING_KEY = JWT_SIGNING_KEY_ENV or SECRET_KEY

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':
    timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME':
    timedelta(days=1),
    'SIGNING_KEY': JWT_SIGNING_KEY,
}


def _validate_fernet_key(value):
    try:
        Fernet(value.encode())
    except Exception as exc:
        raise ImproperlyConfigured(
            "FIELD_ENCRYPTION_KEY must be a valid Fernet key. Generate one with: "
            "python -c \"from cryptography.fernet import Fernet; "
            "print(Fernet.generate_key().decode())\""
        ) from exc


def _validate_production_settings():
    if DEBUG:
        if FIELD_ENCRYPTION_KEY:
            _validate_fernet_key(FIELD_ENCRYPTION_KEY)
        return

    missing = []
    if SECRET_KEY == DEV_SECRET_KEY:
        missing.append("DJANGO_SECRET_KEY")
    if not JWT_SIGNING_KEY_ENV:
        missing.append("JWT_SECRET_KEY")
    if not FIELD_ENCRYPTION_KEY:
        missing.append("FIELD_ENCRYPTION_KEY")
    if not ALLOWED_HOSTS:
        missing.append("DJANGO_ALLOWED_HOSTS")
    if not CORS_ALLOWED_ORIGINS:
        missing.append("DJANGO_CORS_ALLOWED_ORIGINS")
    if not DATABASE_URL:
        missing.append("DATABASE_URL")

    if missing:
        raise ImproperlyConfigured(
            "Missing required production environment variables: "
            + ", ".join(sorted(missing))
        )

    _validate_fernet_key(FIELD_ENCRYPTION_KEY)


_validate_production_settings()

# Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'json': {
            '()': 'api.log_formatter.JSONFormatter',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json' if not DEBUG else 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
