services:
  - type: web
    name: rag-web-app-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: rag-db
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CORS_ALLOWED_ORIGINS
        sync: false
      - key: DJANGO_DB_SSL_REQUIRE
        value: true

databases:
  - name: rag-db
    databaseName: rag_db
    plan: free
