# Generated by Django 6.0.2 on 2026-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chunks',
            field=models.JSONField(default=list),
        ),
    ]
