# Generated by Django 6.0.2 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_userprofile_llm_provider_and_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="llm_model",
            field=models.CharField(default="gemini-2.5-flash", max_length=128),
        ),
    ]

