# Generated by Django 6.0.2 on 2026-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_evaluationdataset_evaluationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfeedback',
            name='failure_tag',
            field=models.CharField(blank=True, choices=[('bad_retrieval', 'Bad Retrieval'), ('hallucination', 'Hallucination'), ('incomplete', 'Incomplete'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
